import React,{useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'

export default function AccountCenter({mode='Profile',user,onBack,onNotify}){
 const [form,setForm]=useState({display_name:user?.user_metadata?.full_name||'',username:'',bio:'',language:'en',timezone:'UTC',appearance:'system',notifications_enabled:true,profile_public:false})
 const [busy,setBusy]=useState(false)
 useEffect(()=>{if(!supabase||!user)return;supabase.from('user_settings').select('*').eq('user_id',user.id).maybeSingle().then(({data})=>{if(data)setForm(v=>({...v,...data}))})},[user])
 const save=async()=>{if(!supabase||!user)return;setBusy(true);try{const payload={...form,user_id:user.id,updated_at:new Date().toISOString()};const {error}=await supabase.from('user_settings').upsert(payload);if(error)throw error;await supabase.from('profiles').update({full_name:form.display_name,updated_at:new Date().toISOString()}).eq('id',user.id);onNotify?.('Account settings saved.')}catch(e){onNotify?.(e.message||'Could not save settings.')}finally{setBusy(false)}}
 return <section className="account-center"><div className="workspace-panel-head"><div><div className="eyebrow"><span className="eyebrow-line"/> {mode.toUpperCase()}</div><h1>{mode==='Profile'?'Your Spectra identity.':'Control your workspace.'}</h1><p>{mode==='Profile'?'Manage the profile information shown across your Spectra workspace.':'Privacy, appearance, notifications and personal AI defaults.'}</p></div><button className="ghost-button" onClick={onBack}>← Back to dashboard</button></div>
 <div className="account-center-grid"><div className="account-card"><div className="large-profile-avatar">{(form.display_name||user?.email||'S').slice(0,2).toUpperCase()}</div><strong>{form.display_name||'Spectra member'}</strong><span>{user?.email}</span><span className="account-role">Verified account</span></div>
 <div className="account-form"><label>Display name<input value={form.display_name||''} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><label>Username<input value={form.username||''} onChange={e=>setForm({...form,username:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'')})} placeholder="yourname"/></label><label>Bio<textarea value={form.bio||''} onChange={e=>setForm({...form,bio:e.target.value})} rows="4" placeholder="Tell people about you"/></label>{mode==='Settings'&&<><label>Appearance<select value={form.appearance} onChange={e=>setForm({...form,appearance:e.target.value})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Language<select value={form.language} onChange={e=>setForm({...form,language:e.target.value})}><option value="en">English</option><option value="fr">French</option><option value="es">Spanish</option></select></label><label className="toggle-row"><input type="checkbox" checked={form.notifications_enabled} onChange={e=>setForm({...form,notifications_enabled:e.target.checked})}/> Enable notifications</label><label className="toggle-row"><input type="checkbox" checked={form.profile_public} onChange={e=>setForm({...form,profile_public:e.target.checked})}/> Make profile discoverable</label></>}<button className="primary-button" disabled={busy} onClick={save}>{busy?'Saving…':'Save changes'} <span>↗</span></button></div></div></section>
}
